[project]
name = "thinking-machines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Mayer" },
    { name = "Kilian Achterberg" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "torch>=2.14.1",
]

[project.scripts]
thinking-machines = "thinking_machines:main"

[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "crates/board_game_pyo3_bindings/Cargo.toml"
python-source = "src"
module-name = "thinking_machines._rust"
bindings-type = "pyo3"

[dependency-groups]
dev = [
    "ruff>=0.16.10",
    "maturin>=1.5,<2.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"

